### ISSUE TITLE
Terms "service" and "application" seem to be used interchangeably

### ISSUE THREAD

**Issue by alvestrand** [coopdanger/ietf-wg-mimi#11]
It is not clear from the charter what is meant by the terms "service" and "application". Some sentences read like they are two names for the same thing, other sentences read like the application is something the end user uses to access the service - meaning that they are different.

Those terms should be defined in the charter before being used, and the text checked to make sure usage is consistent.

**Comment by coopdanger** [comment]
Addressed in [d4401a5](https://github.com/coopdanger/ietf-wg-mimi/commit/d4401a5ede5a7a30d0e53922b4765a3925b8c54c) -- changed to "service" throughout.
