### ISSUE TITLE
Scoping future A/V work

### ISSUE THREAD

**Issue by coopdanger** [coopdanger/ietf-wg-mimi#18]
@zaheduzzaman said:
>it says -
>          In a future phase, the working group may recharter to work on audio and video. The working group will not standardize new audio/video signaling or media protocols but may recommend the use of existing protocols and suites such as SIP and WebRTC.

> If a rechartering is needed to work with AV then why in this charter we are scoping the future work?

**Comment by coopdanger** [comment]
I recommend to delete this sentence to clarify this: "In a future phase, the working group may recharter to work on audio and video."

**Comment by zaheduzzaman** [comment]
> I recommend to delete this sentence to clarify this: "In a future phase, the working group may recharter to work on audio and video."

This would be a good resolution,

**Comment by coopdanger** [comment]
Fixed in [5368adc](https://github.com/coopdanger/ietf-wg-mimi/commit/5368adc2a3f316988ed28db6eb27c94befd7a05d).
