### ISSUE TITLE
Why XMPP does not meet requirements for interoperability?

### ISSUE THREAD

**Issue by soroshsabz** [coopdanger/ietf-wg-mimi#21]
ITNOA

regardless of transport layer and secure layer (such as MLS or ...) my question is, Why XMPP does not meet requirements for interoperability?

thanks

**Comment by rohan-wire** [comment]
1) One of the first work items for MIMI will be to define the requirements. Until there is consensus on those requirements, it is impossible to say that some transport or another meets them.
2) MLS messages have some unique technical needs. XMPP would need a JEP defined to meet those needs. (I don't anticipate that this would be difficult to do.)
3) What if there are say 5 transport protocols that meet the requirements or could be trivially extended to meet the requirements? The WG needs to decide which one is the most suitable. That is also a consensus process.
