### ISSUE TITLE
Where is other informational RFC or Standard RFC md files for contributions?

### ISSUE THREAD

**Issue by soroshsabz** [coopdanger/ietf-wg-mimi#22]
ITNOA

As you know in https://datatracker.ietf.org/doc/bofreq-cooper-more-instant-messaging-interoperability/ you can see some relevant Internet-Drafts for example

Relevant drafts:
* Problem outline:
https://www.ietf.org/archive/id/draft-mahy-mimi-problem-outline-00.html
* Identity concepts:
https://www.ietf.org/archive/id/draft-mahy-mimi-identity-00.html
* Content profile:
https://www.ietf.org/archive/id/draft-mahy-mimi-content-00.html
* Framework for identity mapping:
https://www.ietf.org/archive/id/draft-rosenberg-dispatch-spin-00.html
* Content negotiation for MLS:
https://www.ietf.org/archive/id/draft-mahy-mls-content-neg-00.html

My question is where is the md files of these Internet-Drafts?

**Comment by soroshsabz** [comment]
I suggest adding all direct related informative RFC to this repo or create another GitHub repo for these based on https://github.com/martinthomson/internet-draft-template

**Comment by soroshsabz** [comment]
@coopdanger Did you agree with me? if you want, I can add all of them into this repo with PR

**Comment by soroshsabz** [comment]
@coopdanger Did you have any plan to check issues and PR in this repo? or all of contribution and request and question about the MIMI, must be provide by IETF mailing list?

thanks :)

**Comment by coopdanger** [comment]
We are using https://github.com/ietf-wg-mimi as the WG Github organization.
