### ISSUE TITLE
Why Matrix Message Transport RFC does not relate to this document?

### ISSUE THREAD

**Issue by soroshsabz** [coopdanger/ietf-wg-mimi#23]
ITNOA

Why some RFC like [Matrix Message Transport](https://datatracker.ietf.org/doc/draft-ralston-mimi-matrix-transport) does not added to related documents in BoF?

**Comment by soroshsabz** [comment]
As you can see in BoF, writer try to show all related document about MIMI aspects, so I think referring to draft-ralston-mimi-matrix-transport is useful for BoF.

**Comment by turt2live** [comment]
at the time of the BoF, the draft wasn't submitted. The draft was submitted afterwards, but was graciously included as a pre-draft anyways.

**Comment by soroshsabz** [comment]
Ok, I think it is no problem, we can update BoF and charter to reflect latest related documents.
