### ISSUE TITLE
OAuth is being superceded by GNAP

### ISSUE THREAD

**Issue by erkinalp** [coopdanger/ietf-wg-mimi#3]
> MIMI will communicate with related working groups as needed, including MLS, STIR, OAUTH, and the W3C Verifiable Credentials WG.
> Technology Overlap: MLS, OAUTH, all of ART
> Key Participant Conflict: MLS, OAUTH, TLS, OHAI, PPM, SECDISPATCH, PRIVACYPASS, QUIC, ADD, DPRIVE, IABOPEN, RSWG

Why not GNAP?

**Comment by coopdanger** [comment]
Added GNAP. Thanks!
