### ISSUE TITLE
Need to specify that presence is (in scope / out of scope)

### ISSUE THREAD

**Issue by alvestrand** [coopdanger/ietf-wg-mimi#8]
Presence - the idea that some user can have a continuously updated view of the status of another user - is prevalent in messaging systems. Examples include green dots on rosters, "read points" in conversations, "I am typing a response" indications, and "this user has been inactive for X days".

A common feature here is that the user does not need to send a message to the group to maintain the status; it is derived in some other way (such as being driven by the service provider's view of the user's status).

This should be either in scope, out of scope, or carefully circumscribed.

**Comment by turt2live** [comment]
I believe this is already covered by the charter? The first sentence is:

> The More Instant Messaging Interoperability (MIMI) working group will specify the minimal set of mechanisms required to make modern Internet messaging applications interoperable.

This should mean it's the working group's problem to figure out if presence is required, not the charter's - I think that's correct, as it means the working group can determine which other features might be required, such as reactions, emoji, etc.

**Comment by alvestrand** [comment]
It is "covered by the charter" in the sense that the charter does not include or exclude it. My point is that the charter should either include or exclude it.

Presence services have a tendency to grow with the square of number of users (as network expands, each user's watched presence group also expands), so the scaling factors of presence are quite different from the scaling factors of messaging.

I believe the group will have a greater chance of success if it's out of scope; the failure scenario I want to avoid is having a sensible solution for messaging being blocked from publication because someone points out that presence is not addressed.

**Comment by turt2live** [comment]
Presence can become an uncontrollable problem if left unchecked, but it really does feel like a feature for the working group to discuss rather than explicitly putting it in the charter. It might ultimately be a thing where the WG decides it's important enough to look at it, but then in designing solutions decides its too hard of a problem and defers it.

Though, personally-speaking, I'd agree that leaving presence out of initial considerations would be good, but also there's other features on that list too 😇

**Comment by coopdanger** [comment]
Address ed in [d4401a5](https://github.com/coopdanger/ietf-wg-mimi/commit/d4401a5ede5a7a30d0e53922b4765a3925b8c54c) -- I split the difference and added presence to the features list, but left it open as to whether it will be deemed in scope or out of scope by the WG.

**Comment by alvestrand** [comment]
I am not happy with this decision - it basically leaves us in the same state as before, where the charter neither includes nor excludes something that is known to be both interesting (meaning that people will want to spend resources discussing it) and known to be problematic (meaning that it is likely to attract so much energy that other parts of the work are hampered).

I would be happier if the charter said "presence will not be addressed; adding it requires a charter change".

**Comment by alvestrand** [comment]
The difference between presence and (say) emoji is that presence (as commonly implemented) requires operations that scale with the interconnectedness of the social mesh (O(# of participants * # of watched entities per participant), likely to be O(# of participants^2)) rather than linearly with the number of participants.

**Comment by rohan-wire** [comment]
I am fine saying that presence requires a recharter.

Thanks,
-rohan

*Rohan Mahy  *l  Vice President Engineering, Architecture

Chat: @rohan_wire on Wire



Wire <https://wire.com/en/download/> - Secure team messaging.

*Zeta Project Germany GmbH  *l  Rosenthaler Straße 40,
<https://maps.google.com/?q=Rosenthaler+Stra%C3%9Fe+40,%C2%A0+10178+Berlin,%C2%A0+Germany&entry=gmail&source=g>10178
Berlin,
<https://maps.google.com/?q=Rosenthaler+Stra%C3%9Fe+40,%C2%A0+10178+Berlin,%C2%A0+Germany&entry=gmail&source=g>
Germany
<https://maps.google.com/?q=Rosenthaler+Stra%C3%9Fe+40,%C2%A0+10178+Berlin,%C2%A0+Germany&entry=gmail&source=g>

Geschäftsführer/Managing Director: Alan Duric, Andre Kiehne

HRB 149847 beim Handelsregister Charlottenburg, Berlin

VAT-ID DE288748675

**Comment by coopdanger** [comment]
> I am not happy with this decision - it basically leaves us in the same state as before, where the charter neither includes nor excludes something that is known to be both interesting (meaning that people will want to spend resources discussing it) and known to be problematic (meaning that it is likely to attract so much energy that other parts of the work are hampered).
> 
> I would be happier if the charter said "presence will not be addressed; adding it requires a charter change".

@turt2live Given the above, can you live with putting presence in the “recharger required” section?

**Comment by turt2live** [comment]
I'm unconvinced it's as severe a technical challenge as it's being portrayed, though ultimately I'm not concerned about presence being in or out of scope for the charter.

**Comment by coopdanger** [comment]
Moved presence out of scope in [0f27fcc](https://github.com/coopdanger/ietf-wg-mimi/commit/0f27fcc88b5c207b6ef6d00972762082f59a5bb3).
